name: 2 First GitHub Action.yaml
on:
  workflow_dispatch:
    push:
      branch:
        - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install Requirements
        run: | 
          python -m pip install pip --upgrade
          python -m pip install -r requirements.txt
      - name: Migrate db
        run: |
          python manage.py migrate
